//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class agenda
    {
        public agenda()
        {
            this.notaDeVenta = new HashSet<notaDeVenta>();
            this.pedido = new HashSet<pedido>();
        }
    
        public int agendaID { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
    
        public virtual ICollection<notaDeVenta> notaDeVenta { get; set; }
        public virtual ICollection<pedido> pedido { get; set; }
    }
}
