//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.convenio = new HashSet<convenio>();
            this.prestamoEquipo = new HashSet<prestamoEquipo>();
            this.pedido = new HashSet<pedido>();
            this.venta = new HashSet<venta>();
        }
    
        public int clienteID { get; set; }
        public string nombre { get; set; }
        public string rfc { get; set; }
        public string observaciones { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<convenio> convenio { get; set; }
        public virtual ICollection<prestamoEquipo> prestamoEquipo { get; set; }
        public virtual ICollection<pedido> pedido { get; set; }
        public virtual ICollection<venta> venta { get; set; }
    }
}
