//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.convenio = new HashSet<convenio>();
            this.prestamoEquipo = new HashSet<prestamoEquipo>();
            this.pedido = new HashSet<pedido>();
            this.venta = new HashSet<venta>();
        }
    
        public int clienteID { get; set; }
        public string nombre { get; set; }
        public string rfc { get; set; }
        public string observaciones { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<convenio> convenio { get; set; }
        public virtual ICollection<prestamoEquipo> prestamoEquipo { get; set; }
        public virtual ICollection<pedido> pedido { get; set; }
        public virtual ICollection<venta> venta { get; set; }
    }
}
