//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public clientes()
        {
            this.convenios = new HashSet<convenios>();
            this.prestamoEquipoes = new HashSet<prestamoEquipoes>();
            this.pedidoes = new HashSet<pedidoes>();
        }
    
        public int clienteID { get; set; }
        public string nombre { get; set; }
        public string rfc { get; set; }
        public string observaciones { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<convenios> convenios { get; set; }
        public virtual ICollection<prestamoEquipoes> prestamoEquipoes { get; set; }
        public virtual ICollection<pedidoes> pedidoes { get; set; }
    }
}
