//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class deudas
    {
        public deudas()
        {
            this.notaDeVentas = new HashSet<notaDeVentas>();
            this.pagoes = new HashSet<pagoes>();
        }
    
        public int deudaID { get; set; }
        public Nullable<double> sumatoriatotal { get; set; }
        public Nullable<double> montotal { get; set; }
    
        public virtual ICollection<notaDeVentas> notaDeVentas { get; set; }
        public virtual ICollection<pagoes> pagoes { get; set; }
    }
}
