//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class entradasalidaMateriaprima
    {
        public int EntSalID { get; set; }
        public Nullable<int> materiaPrimaID { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cantidadES { get; set; }
    
        public virtual materiaPrima materiaPrima { get; set; }
    }
}
