//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipo
    {
        public int equipoID { get; set; }
        public Nullable<int> prestamoEquipoID { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> ultimaFechaDeMantenimiento { get; set; }
        public string estatus { get; set; }
    
        public virtual prestamoEquipo prestamoEquipo { get; set; }
    }
}
