//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class materiaPrima
    {
        public materiaPrima()
        {
            this.entradasalidaMateriaprima = new HashSet<entradasalidaMateriaprima>();
            this.productoTerminado = new HashSet<productoTerminado>();
        }
    
        public int materiaPrimaID { get; set; }
        public Nullable<int> productoID { get; set; }
        public string nombreMateria { get; set; }
        public Nullable<int> existencia { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<entradasalidaMateriaprima> entradasalidaMateriaprima { get; set; }
        public virtual ICollection<productoTerminado> productoTerminado { get; set; }
    }
}
