//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public pedido()
        {
            this.productoTerminado = new HashSet<productoTerminado>();
        }
    
        public int pedidoID { get; set; }
        public Nullable<System.DateTime> fechaDeEntrega { get; set; }
        public Nullable<int> clienteID { get; set; }
        public Nullable<int> agendaID { get; set; }
    
        public virtual agenda agenda { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual ICollection<productoTerminado> productoTerminado { get; set; }
    }
}
