//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public pedido()
        {
            this.productoTerminado = new HashSet<productoTerminado>();
        }
    
        public int pedidoID { get; set; }
        public Nullable<System.DateTime> fechaDeEntrega { get; set; }
        public Nullable<int> clienteID { get; set; }
        public Nullable<int> agendaID { get; set; }
    
        public virtual agenda agenda { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual ICollection<productoTerminado> productoTerminado { get; set; }
    }
}
