//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamoEquipoes
    {
        public prestamoEquipoes()
        {
            this.equipoes = new HashSet<equipoes>();
        }
    
        public int prestamoEquipoID { get; set; }
        public Nullable<int> clienteID { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual ICollection<equipoes> equipoes { get; set; }
    }
}
