//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class productoTerminadoES
    {
        public int PDEntSalID { get; set; }
        public Nullable<int> productoID { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> fechaES { get; set; }
        public Nullable<int> cantidadES { get; set; }
    
        public virtual productoTerminado productoTerminado { get; set; }
    }
}
