//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class productoTerminado
    {
        public productoTerminado()
        {
            this.productoTerminadoES = new HashSet<productoTerminadoES>();
            this.venta1 = new HashSet<venta>();
            this.materiaPrima = new HashSet<materiaPrima>();
            this.pedido = new HashSet<pedido>();
            this.venta2 = new HashSet<venta>();
        }
    
        public int productoID { get; set; }
        public Nullable<int> ventaID { get; set; }
        public Nullable<int> pedidoID { get; set; }
        public string nombreProducto { get; set; }
        public string tipo { get; set; }
        public Nullable<int> existencia { get; set; }
        public string materiales { get; set; }
        public string descripcionProducto { get; set; }
        public string venta { get; set; }
    
        public virtual ICollection<productoTerminadoES> productoTerminadoES { get; set; }
        public virtual ICollection<venta> venta1 { get; set; }
        public virtual ICollection<materiaPrima> materiaPrima { get; set; }
        public virtual ICollection<pedido> pedido { get; set; }
        public virtual ICollection<venta> venta2 { get; set; }
    }
}
