//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int usuarioID { get; set; }
        public string nombre { get; set; }
        public string nombreUsuario { get; set; }
        public string contrasena { get; set; }
        public string rol { get; set; }
    }
}
