//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.corteDeDia = new HashSet<corteDeDia>();
            this.productoTerminado1 = new HashSet<productoTerminado>();
        }
    
        public int ventaID { get; set; }
        public Nullable<int> productoId { get; set; }
        public Nullable<int> clienteID { get; set; }
        public Nullable<int> venta1 { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<corteDeDia> corteDeDia { get; set; }
        public virtual productoTerminado productoTerminado { get; set; }
        public virtual ICollection<productoTerminado> productoTerminado1 { get; set; }
    }
}
