//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picachos.Backend.Negocio.EntidadesNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.corteDeDia = new HashSet<corteDeDia>();
            this.productoTerminado1 = new HashSet<productoTerminado>();
        }
    
        public int ventaID { get; set; }
        public Nullable<int> productoID { get; set; }
        public Nullable<int> clienteID { get; set; }
        public Nullable<double> total { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> folio { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<corteDeDia> corteDeDia { get; set; }
        public virtual productoTerminado productoTerminado { get; set; }
        public virtual ICollection<productoTerminado> productoTerminado1 { get; set; }
    }
}
